### ISSUE TITLE
Document that crc32's integer is unsigned

### ISSUE THREAD

**Issue by mattbishop** [napi-rs/node-rs#142]
I'm using crc32c to create checksums that are stored in Postgres as an int. Their ints are signed, and often the result of crc32c() goes outside the bounds of a signed int (4 bytes, -2147483648 to +2147483647) because crc32c() returns an unsigned int value it seems. I can adjust with `crc >>> 0` but it would be nice to document this in the API.

Even better, if the rust lib supports generating unsigned crc values then provide an option to do so.

Thanks for the fast lib!

**Comment by Brooooooklyn** [comment]
> if the rust lib supports generating unsigned crc values then provide an option to do so.

I think this is not possible, because the sse crc32 api only accept `u32`: `https://doc.rust-lang.org/core/arch/x86/fn._mm_crc32_u32.html`

Close via https://github.com/napi-rs/node-rs/commit/6c756b0a7f642aee92d5aa6024893fbe4028d43a

And thanks for your report.
