### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by mhkeller** [napi-rs/node-rs#357]
Would it be possible to get `@node-rs/jieba` working as a client side library for the browser?

**Comment by Brooooooklyn** [comment]
`@node-rs/jieba` couldn't work with browser, but `jieba-rs` could work in browser via `wasm-pack`

**Comment by mhkeller** [comment]
Thanks. Could you point me to that project’s page? I can’t tell which one it is on npm.

**Comment by Brooooooklyn** [comment]
Oh, I mean https://github.com/messense/jieba-rs, it's a rust project, and it need some development work to make it into `wasm`, and so that it could be run in browser. No one have done this for now.

**Comment by JounQin** [comment]
@Brooooooklyn Is there any possible to build this project into `wasm` at the same time? `wasm` can be used in Node too.

**Comment by Brooooooklyn** [comment]
Tracking on https://github.com/napi-rs/napi-rs/issues/796
