### ISSUE TITLE
support ARM v8 crc32c instructions

### ISSUE THREAD

**Issue by mattbishop** [napi-rs/node-rs#370]
It looks like ARMv8 has CRC32C instructions available.

https://elixir.bootlin.com/linux/v4.6/source/arch/arm64/crypto/crc32-arm64.c

**Comment by mattbishop** [comment]
The crc32c crate now supports aarch64: https://github.com/zowens/crc32c/blob/master/src/hw_aarch64.rs

**Comment by Brooooooklyn** [comment]
Close by https://github.com/napi-rs/node-rs/pull/463
