### ISSUE TITLE
Can not find node binding files from @node-rs/jieba-win32-x64-gnu,@node-rs/jieba-win32-x64-msvc and...

### ISSUE THREAD

**Issue by StevenMichael3213** [napi-rs/node-rs#399]
![image](https://user-images.githubusercontent.com/31765462/116523188-4c0b0800-a919-11eb-8f8b-7419c9db29b5.png)

Hello, When I use it in my nodejs project. After I packaged a application for windows use electron-builder. App can work normally on most machines. But this error appeared on a small number of machines. I don't know about "gnu" or "msvc". Do you know the reason for this?

**Comment by Brooooooklyn** [comment]
Hey @StevenMichael3213 , I've met this issue once, and I found it's because windows firewall prevent the `Node.js` to load the ***unsigned dll*** file. In your case, is the `jieba.win32-x64-msvc.node` file in the electron asar folder.

**Comment by StevenMichael3213** [comment]
👍You're right. Today I tried to install nodejs on the computer where the above error occurred and then recompile my application. After installing nodejs, I didn't compile it again, just ran the previous application package and found that no errors were reported. My software is running normally. 😄

But how to make the firewall not prevent nodejs from loading unsigned dll files? Is it the same as my operation above, install nodejs once? It seems a bit out of date. Because some users do not have nodejs installed on their computers. On the other hand, they don't want to install it either.

**Comment by Brooooooklyn** [comment]
> But how to make the firewall not prevent nodejs from loading unsigned dll files?

I know a way is signing the dll file with system trusted cert
