### ISSUE TITLE
[bcrypt] Doesn't work on alpine

### ISSUE THREAD

**Issue by Mokto** [napi-rs/node-rs#46]
I'm still looking into it.

I tried installing gcompat or libc6-compat: 

```
Error relocating /usr/node_modules/@node-rs/bcrypt/bcrypt.linux.node: __register_atfork: symbol not found
```

Without them:
```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/node_modules/@node-rs/bcrypt/bcrypt.linux.node)
```

My dockerfile:

```
FROM node:14-alpine

# Create app directory
RUN mkdir -p /usr
WORKDIR /usr

COPY package*.json ./
RUN apk add --no-cache gcompat \
    && npm install --production
```

**Comment by Mokto** [comment]
Might be related : https://stackoverflow.com/questions/58766740/how-can-i-target-my-rust-application-and-its-dependencies-to-musl

**Comment by Brooooooklyn** [comment]
@Mokto [@node-rs/bcrypt@0.3.0](https://www.npmjs.com/package/@node-rs/bcrypt) should support linux musl, and it tested on `node:12-alpine` and `node:14-alpine`
