### ISSUE TITLE
'loadBinding' in helper will not work in pnpm monorepo

### ISSUE THREAD

**Issue by m1heng** [napi-rs/node-rs#474]
When hoist is turned off in pnpm monorepo, packages which were not listed in package.json will not be accessible to current node path.
This leads a runtime failure like "TypeError: Not compatible with your platform. Error message: Cannot find module '@node-rs/crc32-darwin'"

**Comment by Brooooooklyn** [comment]
Upgrade to latest `@node-rs/crc32`
