### ISSUE TITLE
Denolint CLI command does not fail on error

### ISSUE THREAD

**Issue by zoontek** [napi-rs/node-rs#545]
Hello 👋

First, thanks for these awesome bindings, these are awesome!

I'm having a question / feature request (it might be possible, but I don't know how): Is there a way to fail on error with the `denolint` CLI? I saw that it's possible with the Webpack plugin, but we would like to run `denolint` in our CI and see it fails if there is some errors.

<img width="1297" alt="Screenshot 2021-11-02 at 11 04 49" src="https://user-images.githubusercontent.com/1902323/139826635-25288d39-c187-41ab-9f1d-9bcca475b611.png">

**Comment by Brooooooklyn** [comment]
It's a bug, I'll fix it

**Comment by zoontek** [comment]
Thanks! I found that weird too 😄

**Comment by Brooooooklyn** [comment]
published https://github.com/napi-rs/node-rs/releases/tag/%40node-rs%2Fdeno-lint%401.10.3

**Comment by zoontek** [comment]
We already updated. It works perfectly, thanks for the reactivity!
