### ISSUE TITLE
如何使用loadDict加载自定义词典呢

### ISSUE THREAD

**Issue by 820465323** [napi-rs/node-rs#55]
看.d.ts的参数类型是Buffer而不是引入一个像nodejieba中.utf-8的文件

**Comment by 820465323** [comment]
比如在nodejieba中是这样加载自定义文件的
`import * as jieba from 'nodejieba';
jieba.load({ userDict: `${__dirname}/../../lib/self.utf-8`});`

**Comment by Brooooooklyn** [comment]
```ts
const dict = fs.readFileSync(`${__dirname}/../../lib/self.utf-8`)
```

**Comment by 820465323** [comment]
@Brooooooklyn 
这个执行后抛错


thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', packages/jieba/src/lib.rs:70:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

**Comment by 820465323** [comment]
import * as jieba from '@node-rs/jieba';
import * as fs from 'fs';
jieba.loadDict(fs.readFileSync('/home/zzw/MySelfGitHUb/Private_file/study-node-modul-ts/self.utf-8'));

**Comment by Brooooooklyn** [comment]
底层的 `jieba-rs` 对 UserDict 格式要求比 nodejieba 严格
所以你的 UserDict 格式必须是这样:
```
些許端 2 m
些许 163 d
些许端 2 m
些須 3 d
些须 3 d
亜 20 zg
亝 6 zg
亞 13 zg
亞 5789 j
亞丁 57 nrt
亞丁港 4 ns
```

`nodejieba` 支持这种简单的格式: 

```
云计算
韩玉鉴赏
蓝翔 nz
区块链 10 nz
```

**Comment by Brooooooklyn** [comment]
@messense  Do you consider about support more flexible  format like `cppjieba` does in `jieba-rs`?

**Comment by 820465323** [comment]
非常感谢，使用了您给我提供的格式后，可以正常使用
相比较nodejieba @node-rs/jieba在投入生产有什么注意事项吗？因为我在测试机上部署nodejieba遇到了很多问题，所以选择了@node-rs/jieba

**Comment by messense** [comment]
可以在 https://github.com/messense/jieba-rs 这边开个 issue 提一下你的具体需求。

**Comment by Brooooooklyn** [comment]
@820465323  @node-rs/jieba 目前不支持 `Linux musl` 系的操作系统，比如 `alpine`, 如果你需要运行在 Docker 里面请用 `node:lts-slim` 或者 `node:lts` 镜像。
`@node-rs/jieba` 底层的 `jieba-rs` 已经被广泛使用了，可以放心使用，有任何使用中的问题可以随时提 issue。

**Comment by messense** [comment]
> fatal runtime error: failed to initiate panic, error 5

BTW，这个看起来 node-rs 现在的封装在 Rust 代码 panic 的时候 panic 会跨越 FFI 边界存在 undefined behavior，应该用 `catch_unwind` 规避。

**Comment by messense** [comment]
https://github.com/rust-lang/rfcs/blob/master/text/2797-project-ffi-unwind.md#motivation
