### ISSUE TITLE
Thoughts on glibc/musl vs rustix?

### ISSUE THREAD

**Issue by styfle** [napi-rs/node-rs#594]
Today, we distribute both glibc and musl variants but I think it might be possible to distribute a single binary using rustix.

- Crate: https://crates.io/crates/rustix
- Blog post: https://blog.sunfishcode.online/port-std-to-rustix/
- Additional comments: https://news.ycombinator.com/item?id=29794452

Thoughts?

**Comment by Brooooooklyn** [comment]
@styfle `glibc/libc` are linked by program `linker`, and we can't static link `libc` in our `.node` addon because it is actually a dynamic linked library. 

We can distribute a single `executable file` with `musl.cc` or `rustix`, but it does not work if the target is `dylib`.

**Comment by styfle** [comment]
Oh I see what you mean now

> Addons are dynamically-linked shared objects

https://nodejs.org/api/addons.html#c-addons

That's unfortunate. I'll close this issue 😶

**Comment by styfle** [comment]
I noticed `esbuild` doesn't ship glibc/musl variants so there must be some difference?

https://github.com/evanw/esbuild/blob/20b121e067f3b49ab49ce16c007df66790366c8b/npm/esbuild/package.json#L14-L32

**Comment by Brooooooklyn** [comment]
`esbuild` is an executable binary, it communicates with Node.js via stdio rather than Node-API.

**Comment by styfle** [comment]
Oh yeah 🤦‍♂️
