### ISSUE TITLE
M1 chip running error

### ISSUE THREAD

**Issue by tfzxyinhao** [napi-rs/node-rs#624]
hi there
my project was copied from [package templage](https://github.com/napi-rs/package-template),
`yarn build` and `yarn test` works right, but when other projects require this module, give me the following
 `(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`
![image](https://user-images.githubusercontent.com/444814/158175501-21d55319-d6de-490e-aaaa-abdd455d2815.png)

reproduce steps
1. execute command `yarn link @${module_name}` in the addon module dir
2. execute command `yarn link` in the caller project dir
3. use it `let {xxx} = require('@${module_name}')`

**Comment by tfzxyinhao** [comment]
execute `yarn build` generate the file `xxxx.darwin-x64`
but caller project need `xxx.darwin-arm64`

**Comment by Brooooooklyn** [comment]
You are running x64 version Node.js and build for arm64 version electron

**Comment by tfzxyinhao** [comment]
thanks for the answer, but I still don't understand how to solve it

**Comment by Brooooooklyn** [comment]
`brew install node@16`

**Comment by tfzxyinhao** [comment]
after install new nodejs16 with `brew install node@16`, still generate file 'xxx.darwin-x64.node'

**Comment by Brooooooklyn** [comment]
Run the following command and see what output in your terminal: `node -e "console.log(process.arch)"`

It should be `arm64`. You are running Node.js with the wrong arch if it's `x64`.

**Comment by tfzxyinhao** [comment]
![image](https://user-images.githubusercontent.com/444814/158205796-82a2df68-a3a2-442a-b0ce-7bae44520508.png)

now the node version is the same as you say, but still, generate file 'xxx.darwin-x64.node'

**Comment by Brooooooklyn** [comment]
This is weird, run `rm *.node && cargo clean` and build again.

**Comment by Brooooooklyn** [comment]
I have MacBook Pro 16 M1 Max in my hands, and I can't reproduce it. It generates `*.darwin-arm64.node` after running the yarn build command.

**Comment by tfzxyinhao** [comment]
weird too,  after cleaning the environment, generate *.darwin-x64.node

![image](https://user-images.githubusercontent.com/444814/158209378-b9afc7e7-866d-458f-9b3f-17441fd8ca9c.png)

**Comment by tfzxyinhao** [comment]
does the build command correct ?
![image](https://user-images.githubusercontent.com/444814/158209753-fe752344-3d43-42bc-8da4-0452d1803179.png)

![image](https://user-images.githubusercontent.com/444814/158209617-c3b457f2-e0a5-4a55-a84e-ef5288d4e43d.png)

**Comment by Brooooooklyn** [comment]
Oh what's your default target in `rustup`? You can run `rustup target list` to show them

**Comment by tfzxyinhao** [comment]
maybe the rust version cause generate the incorrect node file
![image](https://user-images.githubusercontent.com/444814/158210478-0e7852ce-26e3-4e74-8631-4d314345f04a.png)

**Comment by Brooooooklyn** [comment]
Run `rustup default stable-aarch64-apple-darwin` should resolve your problem.

**Comment by samuelgja** [comment]
I have same issue, for me do not help anything from above :(

I'am using node 18,
<img width="84" alt="Screenshot 2023-09-26 at 22 47 24" src="https://github.com/napi-rs/node-rs/assets/5537298/6f1f527d-7e70-4712-827b-6c3d99a32d42">
 and rustup:
<img width="260" alt="Screenshot 2023-09-26 at 22 46 48" src="https://github.com/napi-rs/node-rs/assets/5537298/059f6adf-641a-42ef-9b73-4c7cce72509d">

**Comment by Brooooooklyn** [comment]
@samuelgja can you try `DEBUG=napi:* yarn build`?
