### ISSUE TITLE
调用loadDict加载词库报错

### ISSUE THREAD

**Issue by apprat** [napi-rs/node-rs#628]
![QQ截图20220413143813](https://user-images.githubusercontent.com/42712641/163115459-0e14f96b-3550-4e6b-9593-4e9e76fce6f9.png)
调用load开头的均报这个错

**Comment by Brooooooklyn** [comment]
`load` `loadDict` 和 `loadTFIDFDict` 三个函数只能调用其中一个。另外你好像用了 nodemon？直接启动会有报错吗？

**Comment by apprat** [comment]
> 



> `load` `loadDict` 和 `loadTFIDFDict` 三个函数只能调用其中一个。另外你好像用了 nodemon？直接启动会有报错吗？

经过测试 确实是热更新的问题，看起来我需要try去执行load

**Comment by apprat** [comment]
> `load` `loadDict` 和 `loadTFIDFDict` 三个函数只能调用其中一个。另外你好像用了 nodemon？直接启动会有报错吗？

因为我没法判断是否已经加载过了，希望load不抛出错误不执行加载即可或增加一个导出判断是否已加载
