### ISSUE TITLE
deno-lint: cli ignores path

### ISSUE THREAD

**Issue by zachauten** [napi-rs/node-rs#631]
Hope you don't mind me submitting 2 separate issues at once, but I don't think this is related to #630.

It seems the denolint cli ignores the `path` parameter and lints everything recursively, starting at the cwd. Example where I point it at a file with a single script, and it lints a second script in the current directory anyway:

```
~$ tree
.
├── main.js
└── test
    └── main2.js

1 directory, 2 files
~$ npx denolint test
error[require-await]: Async function 'main' has no 'await' expression.
 -->~/test/main2.js:2:1
  |
2 | / async function main() {
3 | | 	console.log('hello world!');
4 | | }
  | |_^
  |
  = help: Remove 'async' keyword from the function or use 'await' expression inside.
error[require-await]: Async function 'main' has no 'await' expression.
 --> ~/test/main.js:2:1
  |
2 | / async function main() {
3 | | 	console.log('hello world!');
4 | | }
  | |_^
  |
  = help: Remove 'async' keyword from the function or use 'await' expression inside. 
```

**Comment by prantlf** [comment]
You can create a file `.eslintignore` with file paths or patterns to ignore as a workaround.

**Comment by hadriann** [comment]
@prantlf - one interesting use case, not covered by the above `.eslintignore` workaround, is linting one specific file at a time. This is especially useful when integrating denolint with editors so that the current file can be automatically linted on save.

**Comment by prantlf** [comment]
@hadriann, yes, if you integrate denolint to an editor, git hook or other tool, which lints a file selection, _and you need to exclude some rules using `.denolint.json`_, there is no workaround.

If you needd the _recommended_ rules enabled and none of them excluded, you can write an editor plugin as [it is documented](https://github.com/napi-rs/node-rs/tree/main/packages/deno-lint#usage):

```js
import { readFile } from 'fs/promises'
import { lint } from '@node-rs/deno-lint'

const filepath = 'lib/index.js'
const source = await readFile(filepath)

try {
  const warnings = lint(filepath, source)
  for (const warning of warnings) console.warn(warning)
} catch ({ message }) {
  console.error(message)
}
```
