### ISSUE TITLE
winserver2012 R2 无法使用，是否还缺少环境没安装，同样代码其他电脑正常。

### ISSUE THREAD

**Issue by guess127** [napi-rs/node-rs#641]
winserver2012 R2 无法使用，是否还缺少环境没安装，同样代码其他电脑正常。
系统
![win-ver](https://raw.githubusercontent.com/guess127/updater/master/imgs/win-ver.png)
示例代码
![vs-demo-code](https://raw.githubusercontent.com/guess127/updater/master/imgs/vs-demo-code.png)
运行失败
![build-error](https://raw.githubusercontent.com/guess127/updater/master/imgs/build-err.png)

**Comment by Brooooooklyn** [comment]
See https://github.com/napi-rs/node-rs/issues/632#issuecomment-1214287646
