### ISSUE TITLE
The word segmentation result is different with which from Python or Java pkg

### ISSUE THREAD

**Issue by Sheepeer** [napi-rs/node-rs#653]
When I use node-rs to get segmentation result of Chinese '同方威视股份有限公司', the result is different with python/java jieba pkg, which are as follows:
node-rs:
![image](https://user-images.githubusercontent.com/78125933/206132429-69e00153-8b90-4a17-8da2-89a17a96ad68.png)
python/java jieba pkg:
![image](https://user-images.githubusercontent.com/78125933/206132572-1bd52811-1ab4-43c8-a3d3-a6a6f2f8da1b.png)

Could anyone tell me what's the problem (maybe it is not a problem)?

**Comment by Brooooooklyn** [comment]
I think it's implementation differences between jieba-rs and jieba in other languages /cc @messense

**Comment by messense** [comment]
jieba-rs uses the dict and hmm model from cppjieba so it can differ from python/java.
