### ISSUE TITLE
extract 可以產生 weight-value 嗎

### ISSUE THREAD

**Issue by jtjin** [napi-rs/node-rs#79]
您好,
請問extract可以產生 weight-value 嗎?  類似 node-jieba 

ex : 
//[ { word: 'CEO', weight: 11.739204307083542 },
//  { word: '升职', weight: 10.8561552143 },
//  { word: '加薪', weight: 10.642581114 },
//  { word: '巅峰', weight: 9.49395840471 } ]

**Comment by Brooooooklyn** [comment]
@messense seems `jieba-rs` doesn't provide weight value in extract API

**Comment by messense** [comment]
@Brooooooklyn Yes, opened an issue https://github.com/messense/jieba-rs/issues/73 to track this.

**Comment by messense** [comment]
Available in jieba-rs [v0.6.0-alpha.1](https://crates.io/crates/jieba-rs/0.6.0-alpha.1)

**Comment by jtjin** [comment]
Nice!! Many thanks!!

**Comment by Brooooooklyn** [comment]
@jtjin  try `@node-rs/jieba@0.4.0-alpha.0 `

**Comment by jtjin** [comment]
It works!!
