### ISSUE TITLE
Unsupported platform for @node-rs/argon2-wasm32-wasi@1.8.0: wanted {"cpu":"wasm32"} (current: {"cpu":"x64"})

### ISSUE THREAD

**Issue by davidyuk** [napi-rs/node-rs#810]
I'm getting the above error trying to install this package as
```
npm i @node-rs/argon2-wasm32-wasi
```
it works if I add `--force` flag
```
npm i @node-rs/argon2-wasm32-wasi --force
```
The problem is
https://github.com/napi-rs/node-rs/blob/ee3defdfa60eb8b9da692d0b92387e513c3acb81/packages/argon2/npm/wasm32-wasi/package.json#L4-L6
It is not set correctly, because wasm actually can be executed on `x64` and other platforms. I think the best would be to omit `cpu` key at all. NPM version I'm using is 10.2.4.

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#cpu

**Comment by Brooooooklyn** [comment]
`npm i @node-rs/argon2-wasm32-wasi --cpu=wasm32`, see https://github.com/napi-rs/napi-rs/issues/1794 and https://github.com/napi-rs/node-rs/issues/792 for the context

**Comment by davidyuk** [comment]
Sounds good to me. I'm planning to use this package in our sdk, will report if I have any other issues. Thank you!
