### ISSUE TITLE
Module parse failed: Unexpected character '�'

### ISSUE THREAD

**Issue by dongdiep00** [napi-rs/node-rs#814]
There is a problem when I use with nextjs 14 and nodejs 18 ,please help me solve this problem. Thanks
![Screenshot 2024-03-27 at 19 45 21](https://github.com/napi-rs/node-rs/assets/111213505/f66cba71-29af-4c8e-8163-a2a94d1dbcce)

**Comment by Brooooooklyn** [comment]
See https://github.com/napi-rs/use-napi-rs-packages-with-bundlers for example
