### ISSUE TITLE
[xxhash] Can't resolve `@node-rs/xxhash-wasm32-wasi`

### ISSUE THREAD

**Issue by folkvir** [napi-rs/node-rs#834]
Hello! I'm trying to build using `rspack` a bundle (target: browser) of an open-source Typescript package (https://github.com/Callidon/bloom-filters/tree/next/4.0.0):
* Locally after installation I get the package `@node-rs/xxhash` and `@node-rs/xxhash-darwin-amd64`. Tests are working correctly because it uses the darwin one. 
* But building using `rspack` leads to `Can't resolve '@node-rs/xxhash-wasm32-wasi'`.  it follows correctly the browser field but since I do not have the pakcage installed it cannot be resolved... If I try to install the package directly I get the following error `error @node-rs/xxhash-wasm32-wasi@1.7.3: The CPU architecture "arm64" is incompatible with this module.
error Found incompatible module.`

Do you have any tips on how to finish this build? 🤔

**Comment by Brooooooklyn** [comment]
See https://github.com/napi-rs/node-rs/issues/810

**Comment by folkvir** [comment]
`yarn add -P  @node-rs/xxhash-wasm32-wasi --ignore-platform` 👍 
Now the problem is on the `rspack` side with their new wasm loader!
