### ISSUE TITLE
External returns {};

### ISSUE THREAD

**Issue by Elysian10** [napi-rs/node-rs#853]
#[napi]
fn create_source_map(length: u32) -> External<Buffer> {
  External::new(vec![0; length as usize].into())
}
import { createSourceMap } from './index.js'
const bufferExternal = createSourceMap(10);
//returns {}, expected ExternalObject.

Arch Linix, vs code with CodeLLDB.

**Comment by Brooooooklyn** [comment]
@Elysian10 yes, the `ExternalObject` don't have a name in the JavaScript side, it's just a type name in `.d.ts`
