### ISSUE TITLE
Nextjs 14 with @node-rs/argon2: Failed to load native binding

### ISSUE THREAD

**Issue by vladdg-dev** [napi-rs/node-rs#918]
# Issue Title
Failed to load native binding

## Description
Once I use the `hash` method from `@node-rs/argon2`, I get the following: `Error: Failed to load native binding`

## Steps to Reproduce
1. Go to '/register'
2. Enter username and password
3. Click **Register**

## Expected Behavior
I should see the hashed password in the dev console

## Actual Behavior
Throws error

## Screenshots
![image](https://github.com/user-attachments/assets/3bf985ec-5bba-41eb-ad02-1a005150cc55)

## Environment
- **OS:** Tried on docker container and Linux mint
- **Browser:** All of them

## Additional Context
This is the repo: https://github.com/vladdg-dev/node-rs-argon2-error
It's basically a brand new Nextjs project with a single added page `/register` that's using `hash`

**Comment by Brooooooklyn** [comment]
See https://github.com/eisberg-labs/nextjs-node-loader/blob/main/examples/next-14/next.config.mjs

**Comment by Infiee** [comment]
> > See https://github.com/eisberg-labs/nextjs-node-loader/blob/main/examples/next-14/next.config.mjs
> 
> @Brooooooklyn Thanks, but I upgraded to Next 15 and that error doesn't show that error anymore, instead it shows this: ![image](https://private-user-images.githubusercontent.com/69238278/380791822-bd411122-5296-40bf-8e12-b769c22f22e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTk5NzQsIm5iZiI6MTczMDE5OTY3NCwicGF0aCI6Ii82OTIzODI3OC8zODA3OTE4MjItYmQ0MTExMjItNTI5Ni00MGJmLThlMTItYjc2OWMyMmYyMmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDExMDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZDk0OTcwZjZlNWY5MjljOTM1ZDE1YzAxMmIzZDJiYTZhZmU2MjMyMDk4NDI2MjQ2OTU2OGUyOTg5MDQ4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jqMncj5omXAyBMW1hCmQDRQGSd3RVMNXySI6_xm48y0)

I have found a solution by placing @ node rs/bcrypt on the server and using API requests to avoid issues caused by client loading. this is my code...

```ts
// password.ts

import bcrypt from "@node-rs/bcrypt";
export const hashPassword = async (password: string, saltRounds = 10) => {
  return bcrypt.hash(`${password}`, saltRounds);
};

export const comparePassword = async (
  password: string,
  hashPassword: string
) => {
  return bcrypt.compare(`${password}`, hashPassword);
};
```

```ts
// api route
import { NextRequest } from "next/server";

import { comparePassword } from "@/lib/password";
import { prisma } from "@/lib/prisma";

export const POST = async (req: NextRequest) => {
  const body = await req.json();
  const user = await checkUser(body.email, body.password);
  if (user) {
    return Response.json(
      { data: user, message: "Authenticated" },
      { status: 200 }
    );
  } else {
    return Response.json({ message: "Not authenticated" }, { status: 401 });
  }
};

async function checkUser(email: string, password: string) {
  const user = await prisma.user.findUnique({
    where: { email: email },
  });
  if (!user) return null;
  if (await comparePassword(password, user.password)) {
    return user;
  } else {
    throw Error("The password is incorrect, please re-enter.");
  }
}
```

```ts
// next auth config
Credentials({
    name: "Credentials",
    credentials: {
      email: {
        label: "username",
        type: "text",
        placeholder: "please input username",
      },
      password: {
        label: "password",
        type: "password",
        placeholder: "please input password",
      },
    },
    async authorize(credentials, req) {
      console.log("credentials---", credentials);
      if (!credentials?.email || !credentials?.password) {
        return null;
      }
      const { email, password } = credentials as {
        email: string;
        password: string;
      };
      // TODO: look this, fetch api
      const user = await fetch(`${process.env.NEXTAUTH_URL}/api/user`, {
        method: "POST",
        body: JSON.stringify({ email, password }),
      }).then((res) => res.json());
      console.log("auth - user---", user);
      if (user?.data) {
        return user.data;
      } else {
        return null;
      }
    },
}),
```

**Comment by vladdg-dev** [comment]
@Brooooooklyn Thank you, but I'd like to ask you what is the underlying issue? And is it an issue with @node-rs, or next-auth?

**Comment by Infiee** [comment]
> @Infiee Thank you, but I'd like to ask you what is the underlying issue? And is it an issue with @node-rs, or next-auth?

Maybe @node-rs/bcrypt can only run on the server-side of Node.js. After API processing, I tested the development and packaging, and everything runs normally.

**Comment by vladdg-dev** [comment]
Problem solved. @node-rs/argon2 is not Edge compatible and I had to follow this guide: https://authjs.dev/guides/edge-compatibility
