### ISSUE TITLE
Broken benchmark link on npmjs?

### ISSUE THREAD

**Issue by melroy89** [napi-rs/node-rs#925]
On: https://www.npmjs.com/package/@node-rs/argon2

> 
> Benchmarks
> See [benchmark/](https://github.com/napi-rs/node-rs/blob/HEAD/benchmark/argon2.js).

The link to the benchmark is broken, it doesn't exists anymore!?

You might want to update or remove this.

**Comment by millette** [comment]
@melroy89 It was moved to <https://github.com/napi-rs/node-rs/blob/main/packages/argon2/benchmark/argon2.ts>

**Comment by melroy89** [comment]
Yes. But somebody still need to update the link on npm.

**Comment by millette** [comment]
That will only happen with the next release. When will that be? Your guess is as good as mine :-)

**Comment by melroy89** [comment]
Assuming there will be a new release.. CLosing the ticket as "solved" for now..
